const authTypes = {
    AUTH_LOADING: 'AUTH_LOADING',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
};

export default authTypes;
