const types = {
    AUTH_LOADING: 'AUTH_LOADING',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    GET_MEETUPS: 'GET_MEETUPS',
    MEETUPS_LOADING: 'MEETUPS_LOADING',
    MEETUPS_ERROR: 'MEETUPS_ERROR'
};

export default types;
