const types = {
    AUTH_LOADING: 'AUTH_LOADING',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    GET_MEETUPS: 'GET_MEETUPS',
    MEETUPS_LOADING: 'MEETUPS_LOADING',
    MEETUPS_ERROR: 'MEETUPS_ERROR',
    CREATE_MEETUP_LOADING: 'CREATE_MEETUP_LOADING',
    CREATE_MEETUP: 'CREATE_MEETUP',
    CREATE_MEETUP_ERROR: 'CREATE_MEETUP_ERROR',
    CLEAR_CREATE_ERROR: 'CLEAR_CREATE_ERROR',
    CLEAR_CREATED: 'CLEAR_CREATED',
    SHOW_CREATE_MODAL: 'SHOW_CREATE_MODAL',
    CLOSE_CREATE_MODAL: 'CLOSE_CREATE_MODAL',
    ONE_MEETUP_LOADING: 'ONE_MEETUP_LOADING',
    ONE_MEETUP_SUCCESS: 'ONE_MEETUP_SUCCESS',
    ONE_MEETUP_ERROR: 'ONE_MEETUP_ERROR',
    TOP_QUESTIONS: 'TOP_QUESTIONS'
};

export default types;
